global:
  postgresql:
    existingSecret: postgres-secret
    postgresqlUsernameKey: postgresql-username
    postgresqlPasswordKey: postgresql-username
    postgresqlDatabase: "budgetapp"

persistence:
  enabled: true
  size: 500Mi

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
